//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNo
    {
        public long id { get; set; }
        public Nullable<long> Phieu { get; set; }
        public string SanPham { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public string DonViTinh { get; set; }
    
        public virtual PhieuNo PhieuNo { get; set; }
    }
}
