//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuBaoGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuBaoGia()
        {
            this.ChiTietPhieuBaoGias = new HashSet<ChiTietPhieuBaoGia>();
        }
    
        public long id { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<long> DonViBaoGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuBaoGia> ChiTietPhieuBaoGias { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
