//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNo()
        {
            this.ChiTietPhieuNoes = new HashSet<ChiTietPhieuNo>();
        }
    
        public long id { get; set; }
        public string MaSo { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<long> KhachHang { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<double> DaTra { get; set; }
        public Nullable<double> ConNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNo> ChiTietPhieuNoes { get; set; }
        public virtual KhachHang KhachHang1 { get; set; }
    }
}
