// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VNSHOP.Data.Models;

namespace VNSHOP.Data.Migrations
{
    [DbContext(typeof(QLBHContext))]
    partial class QLBHContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VNSHOP.Data.Models.ChiTietPhieuBanHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DonViTinh")
                        .HasColumnType("text");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double?>("GiamGia")
                        .HasColumnType("float");

                    b.Property<long?>("Phieu")
                        .HasColumnType("bigint");

                    b.Property<long?>("SanPham")
                        .HasColumnType("bigint");

                    b.Property<double?>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Phieu");

                    b.HasIndex("SanPham");

                    b.ToTable("ChiTietPhieuBanHang");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.ChiTietPhieuBaoGium", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<long?>("Phieu")
                        .HasColumnType("bigint");

                    b.Property<int?>("SanPham")
                        .HasColumnType("int");

                    b.Property<string>("SoLuong")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.HasIndex("Phieu");

                    b.ToTable("ChiTietPhieuBaoGia");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.ChiTietPhieuNhapKho", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<long?>("Phieu")
                        .HasColumnType("bigint");

                    b.Property<long?>("SanPham")
                        .HasColumnType("bigint");

                    b.Property<double?>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Phieu");

                    b.HasIndex("SanPham");

                    b.ToTable("ChiTietPhieuNhapKho");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.ChiTietPhieuNo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<long?>("Phieu")
                        .HasColumnType("bigint");

                    b.Property<string>("SanPham")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double?>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Phieu");

                    b.ToTable("ChiTietPhieuNo");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.DonViTinh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDonVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DonViTinh");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.DonViTinhSanPham", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DonViTinh")
                        .HasColumnType("bigint");

                    b.Property<double?>("GiaLe")
                        .HasColumnType("float");

                    b.Property<double?>("GiaSi")
                        .HasColumnType("float");

                    b.Property<long?>("SanPham")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinh");

                    b.HasIndex("SanPham");

                    b.ToTable("DonViTinh_SanPham");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.Huyen", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("Tinh")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Tinh");

                    b.ToTable("Huyen");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.KhachHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("Huyen")
                        .HasColumnType("bigint");

                    b.Property<int?>("Loai")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("Tinh")
                        .HasColumnType("bigint");

                    b.Property<long?>("Xa")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Huyen");

                    b.HasIndex("Tinh");

                    b.HasIndex("Xa");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.KhoHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenKho")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("KhoHang");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.KhoHangSanPham", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("KhoHang")
                        .HasColumnType("bigint");

                    b.Property<long?>("SanPham")
                        .HasColumnType("bigint");

                    b.Property<double?>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KhoHang");

                    b.ToTable("KhoHang_SanPham");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.NhanVien", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoVaTen")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuBanHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("KhachHang")
                        .HasColumnType("bigint");

                    b.Property<int?>("Loai")
                        .HasColumnType("int");

                    b.Property<string>("MaSo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<long?>("NhanVien")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("KhachHang");

                    b.ToTable("PhieuBanHang");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuBaoGium", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DonViBaoGia")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DonViBaoGia");

                    b.ToTable("PhieuBaoGia");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuNhapKho", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaSo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<long?>("NhapCungCap")
                        .HasColumnType("bigint");

                    b.Property<double?>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NhapCungCap");

                    b.ToTable("PhieuNhapKho");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuNo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("ConNo")
                        .HasColumnType("float");

                    b.Property<double?>("DaTra")
                        .HasColumnType("float");

                    b.Property<long?>("KhachHang")
                        .HasColumnType("bigint");

                    b.Property<string>("MaSo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("date");

                    b.Property<bool?>("TinhTrang")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KhachHang");

                    b.ToTable("PhieuNo");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.SanPham", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("DonViTinh")
                        .HasColumnType("bigint");

                    b.Property<double?>("GiaLe")
                        .HasColumnType("float");

                    b.Property<double?>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<double?>("GiaSi")
                        .HasColumnType("float");

                    b.Property<byte[]>("HinhAnh")
                        .HasColumnType("image");

                    b.Property<bool?>("KichHoat")
                        .HasColumnType("bit");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgaySanXuat")
                        .HasColumnType("date");

                    b.Property<long?>("QuanLyTonKho")
                        .HasColumnType("bigint");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double?>("ThueVat")
                        .HasColumnType("float")
                        .HasColumnName("ThueVAT");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinh");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.TaiKhoan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MatKhau")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<long?>("NhanVien")
                        .HasColumnType("bigint");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVien");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.ThongTinDonVi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("KyTen")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength(true);

                    b.Property<string>("TenDonVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.ToTable("ThongTinDonVi");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.Tinh", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tinh");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.Xa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Huyen")
                        .HasColumnType("bigint");

                    b.Property<string>("Ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Huyen");

                    b.ToTable("Xa");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.ChiTietPhieuBanHang", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.PhieuBanHang", "PhieuNavigation")
                        .WithMany("ChiTietPhieuBanHangs")
                        .HasForeignKey("Phieu")
                        .HasConstraintName("FK_ChiTietPhieuBanHang_PhieuBanHang");

                    b.HasOne("VNSHOP.Data.Models.SanPham", "SanPhamNavigation")
                        .WithMany("ChiTietPhieuBanHangs")
                        .HasForeignKey("SanPham")
                        .HasConstraintName("FK_ChiTietPhieuBanHang_SanPham");

                    b.Navigation("PhieuNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.ChiTietPhieuBaoGium", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.PhieuBaoGium", "PhieuNavigation")
                        .WithMany("ChiTietPhieuBaoGia")
                        .HasForeignKey("Phieu")
                        .HasConstraintName("FK_ChiTietPhieuBaoGia_PhieuBaoGia");

                    b.Navigation("PhieuNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.ChiTietPhieuNhapKho", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.PhieuNhapKho", "PhieuNavigation")
                        .WithMany("ChiTietPhieuNhapKhos")
                        .HasForeignKey("Phieu")
                        .HasConstraintName("FK_ChiTietPhieuNhapKho_PhieuNhapKho");

                    b.HasOne("VNSHOP.Data.Models.SanPham", "SanPhamNavigation")
                        .WithMany("ChiTietPhieuNhapKhos")
                        .HasForeignKey("SanPham")
                        .HasConstraintName("FK_ChiTietPhieuNhapKho_SanPham");

                    b.Navigation("PhieuNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.ChiTietPhieuNo", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.PhieuNo", "PhieuNavigation")
                        .WithMany("ChiTietPhieuNos")
                        .HasForeignKey("Phieu")
                        .HasConstraintName("FK_ChiTietPhieuNo_PhieuNo");

                    b.Navigation("PhieuNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.DonViTinhSanPham", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.DonViTinh", "DonViTinhNavigation")
                        .WithMany("DonViTinhSanPhams")
                        .HasForeignKey("DonViTinh")
                        .HasConstraintName("FK_DonViTinh_SanPham_DonViTinh");

                    b.HasOne("VNSHOP.Data.Models.SanPham", "SanPhamNavigation")
                        .WithMany("DonViTinhSanPhams")
                        .HasForeignKey("SanPham")
                        .HasConstraintName("FK_DonViTinh_SanPham_SanPham1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DonViTinhNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.Huyen", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.Tinh", "TinhNavigation")
                        .WithMany("Huyens")
                        .HasForeignKey("Tinh")
                        .HasConstraintName("FK_Huyen_Tinh");

                    b.Navigation("TinhNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.KhachHang", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.Huyen", "HuyenNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("Huyen")
                        .HasConstraintName("FK_KhachHang_Huyen");

                    b.HasOne("VNSHOP.Data.Models.Tinh", "TinhNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("Tinh")
                        .HasConstraintName("FK_KhachHang_Tinh");

                    b.HasOne("VNSHOP.Data.Models.Xa", "XaNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("Xa")
                        .HasConstraintName("FK_KhachHang_Xa");

                    b.Navigation("HuyenNavigation");

                    b.Navigation("TinhNavigation");

                    b.Navigation("XaNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.KhoHangSanPham", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.KhoHang", "KhoHangNavigation")
                        .WithMany("KhoHangSanPhams")
                        .HasForeignKey("KhoHang")
                        .HasConstraintName("FK_KhoHang_SanPham_KhoHang");

                    b.HasOne("VNSHOP.Data.Models.SanPham", "KhoHang1")
                        .WithMany("KhoHangSanPhams")
                        .HasForeignKey("KhoHang")
                        .HasConstraintName("FK_KhoHang_SanPham_SanPham");

                    b.Navigation("KhoHang1");

                    b.Navigation("KhoHangNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuBanHang", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.KhachHang", "KhachHangNavigation")
                        .WithMany("PhieuBanHangs")
                        .HasForeignKey("KhachHang")
                        .HasConstraintName("FK_PhieuBanHang_KhachHang");

                    b.Navigation("KhachHangNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuBaoGium", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.KhachHang", "DonViBaoGiaNavigation")
                        .WithMany("PhieuBaoGia")
                        .HasForeignKey("DonViBaoGia")
                        .HasConstraintName("FK_PhieuBaoGia_KhachHang");

                    b.Navigation("DonViBaoGiaNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuNhapKho", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.KhachHang", "NhapCungCapNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("NhapCungCap")
                        .HasConstraintName("FK_PhieuNhapKho_KhachHang");

                    b.Navigation("NhapCungCapNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuNo", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.KhachHang", "KhachHangNavigation")
                        .WithMany("PhieuNos")
                        .HasForeignKey("KhachHang")
                        .HasConstraintName("FK_PhieuNo_KhachHang");

                    b.Navigation("KhachHangNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.SanPham", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.DonViTinh", "DonViTinhNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("DonViTinh")
                        .HasConstraintName("FK_SanPham_DonViTinh");

                    b.Navigation("DonViTinhNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.TaiKhoan", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.NhanVien", "NhanVienNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("NhanVien")
                        .HasConstraintName("FK_TaiKhoan_NhanVien");

                    b.Navigation("NhanVienNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.Xa", b =>
                {
                    b.HasOne("VNSHOP.Data.Models.Huyen", "HuyenNavigation")
                        .WithMany("Xas")
                        .HasForeignKey("Huyen")
                        .HasConstraintName("FK_Xa_Huyen");

                    b.Navigation("HuyenNavigation");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.DonViTinh", b =>
                {
                    b.Navigation("DonViTinhSanPhams");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.Huyen", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("Xas");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.KhachHang", b =>
                {
                    b.Navigation("PhieuBanHangs");

                    b.Navigation("PhieuBaoGia");

                    b.Navigation("PhieuNhapKhos");

                    b.Navigation("PhieuNos");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.KhoHang", b =>
                {
                    b.Navigation("KhoHangSanPhams");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.NhanVien", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuBanHang", b =>
                {
                    b.Navigation("ChiTietPhieuBanHangs");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuBaoGium", b =>
                {
                    b.Navigation("ChiTietPhieuBaoGia");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuNhapKho", b =>
                {
                    b.Navigation("ChiTietPhieuNhapKhos");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.PhieuNo", b =>
                {
                    b.Navigation("ChiTietPhieuNos");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietPhieuBanHangs");

                    b.Navigation("ChiTietPhieuNhapKhos");

                    b.Navigation("DonViTinhSanPhams");

                    b.Navigation("KhoHangSanPhams");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.Tinh", b =>
                {
                    b.Navigation("Huyens");

                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("VNSHOP.Data.Models.Xa", b =>
                {
                    b.Navigation("KhachHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
